language: csharp
mono: none
dotnet: 3.1

install:
- dotnet restore ContestWinnerFromCsv

script:
 - dotnet build ContestWinnerFromCsv
 - dotnet build ContestWinnerFromCsv.Tests
 - dotnet test ContestWinnerFromCsv.Tests/ContestWinnerFromCsv.Tests.csproj